/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.21
 * Generated at: 2019-12-23 05:20:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.manage;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class manage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP 只允许 GET、POST 或 HEAD。Jasper 还允许 OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

String path = request.getContextPath();
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("  <head> \r\n");
      out.write("    <title>Manage</title>      \r\n");
      out.write("    <base href=\"");
      out.print(basePath);
      out.write("\">\r\n");
      out.write("    <meta name=\"description\" content=\"\">\r\n");
      out.write("    <meta name=\"author\" content=\"\">\r\n");
      out.write("\t<meta http-equiv=\"pragma\" content=\"no-cache\">\r\n");
      out.write("\t<meta http-equiv=\"cache-control\" content=\"no-cache\">\r\n");
      out.write("\t<meta http-equiv=\"expires\" content=\"0\">    \r\n");
      out.write("\t<meta http-equiv=\"keywords\" content=\"keyword1,keyword2,keyword3\">\r\n");
      out.write("\t<meta http-equiv=\"description\" content=\"This is my page\">\r\n");
      out.write("\t<link href=\"bootstrap-3.3.7-dist/css/bootstrap.css\" rel=\"stylesheet\">\r\n");
      out.write("\t<link href=\"source/css/dashboard.css\" rel=\"stylesheet\">\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"source/js/jquery-3.4.0.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"source/js/vue.js\"></script>\r\n");
      out.write("\t<!--\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"styles.css\">\r\n");
      out.write("\t-->\r\n");
      out.write("  </head>\r\n");
      out.write("  \r\n");
      out.write("  <style type=\"text/css\">\r\n");
      out.write("\t  body{\r\n");
      out.write("\r\n");
      out.write("\t  }\r\n");
      out.write("\t  #logininfo{\r\n");
      out.write("\t\t  color: aliceblue;\r\n");
      out.write("\t\t  float: right;\r\n");
      out.write("\t  }\r\n");
      out.write("\t  /* !important 表示此样式优先于内置样式*/\r\n");
      out.write("\t  .nav-1{\r\n");
      out.write("\t\t  font-size: 15px !important;\r\n");
      out.write("\t  }\r\n");
      out.write("\t    /*鼠标浮动*/\r\n");
      out.write("\t  .nav-1 a:hover{\r\n");
      out.write("\t\t  background-color:#353333 !important;\r\n");
      out.write("\t  }\r\n");
      out.write("\t    /*已访问*/\r\n");
      out.write("\t  .nav-1 a:visited{\r\n");
      out.write("\t\t  background-color:#353333 !important;\r\n");
      out.write("\t  }\r\n");
      out.write("\t  .active-1 a:focus{\r\n");
      out.write("\t\t  color:aliceblue !important;\r\n");
      out.write("\t  }\r\n");
      out.write("\t</style>\t\r\n");
      out.write("  <body onLoad=\"load()\">\r\n");
      out.write("\t");

	  	String msg = request.getParameter("msg");
	  	
	  	if(msg !=null && msg.equals("1")){
	  
      out.write("\r\n");
      out.write("\t\t<script type=\"text/javascript\" data-genuitec-lp-enabled=\"false\" data-genuitec-file-id=\"wc3-0\" data-genuitec-path=\"/RoomManage/WebRoot/index.jsp\">\r\n");
      out.write("\t\t\talert(\"成功修改房价\");\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t  ");

	  	}else if(msg !=null && msg.equals("2")){
	  
      out.write("\r\n");
      out.write("\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\talert(\"成功添加房间\");\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t  ");

	  	}else if(msg !=null && msg.equals("3")){
	  
      out.write("\r\n");
      out.write("\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\talert(\"成功删除房间\");\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t  ");

	  	}
	  
      out.write("\r\n");
      out.write("    <nav class=\"navbar navbar-inverse navbar-fixed-top\">\r\n");
      out.write("      <div class=\"container-fluid\">\r\n");
      out.write("        <div class=\"navbar-header\">\r\n");
      out.write("          <button type=\"button\" class=\"navbar-toggle collapsed\" data-toggle=\"collapse\" data-target=\"#navbar\" aria-expanded=\"false\" aria-controls=\"navbar\">\r\n");
      out.write("            <span class=\"sr-only\">Toggle navigation</span>\r\n");
      out.write("            <span class=\"icon-bar\"></span>\r\n");
      out.write("            <span class=\"icon-bar\"></span>\r\n");
      out.write("            <span class=\"icon-bar\"></span>\r\n");
      out.write("          </button>\r\n");
      out.write("          <a class=\"navbar-brand\">Manage</a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div id=\"navbar\" class=\"collapse navbar-collapse\" >\r\n");
      out.write("          <ul class=\"nav navbar-nav\"style=\"float: left\">\r\n");
      out.write("            <li class=\"active\"><a href=\"#\">Home</a></li>\r\n");
      out.write("            <li><a href=\"#contact\">Help</a></li>\r\n");
      out.write("          </ul>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t  <ul class=\"nav navbar-nav\"style=\"float: right\">\r\n");
      out.write("            <li class=\"active dropdown\"><a class=\"dropdown-toggle\" data-toggle=\"dropdown\">");
      out.print(session.getAttribute("user") );
      out.write("<span class=\"caret\"></a>\r\n");
      out.write("\t\t\t\t<ul class=\"dropdown-menu\" role=\"menu\">\r\n");
      out.write("\t\t\t\t\t<li class=\"dropdown-header\">Account</li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"servlet\\exit\">Logout</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"divider\"></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("            <li><a>About</a></li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </div><!--/.nav-collapse -->\r\n");
      out.write("      </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("\r\n");
      out.write("     <div class=\"container-fluid\">\r\n");
      out.write("      <div class=\"row\">\r\n");
      out.write("        <div class=\"col-sm-3 col-md-2 sidebar\">\r\n");
      out.write("\t\t\t<p style=\"color:cornsilk; font-size: 25px;\">ManageCenter</p>\r\n");
      out.write("          <ul class=\"nav nav-1 nav-sidebar\">\r\n");
      out.write("            <li><a href=\"manage/manage.jsp#\">Main</a></li>\r\n");
      out.write("            <li><a href=\"manage/search.jsp#\">Search</a></li>\r\n");
      out.write("            <li><a href=\"manage/inport.jsp#\">MoveIn</a></li>\r\n");
      out.write("            <li><a href=\"manage/export.jsp#\">MoveOut</a></li>\r\n");
      out.write("          </ul>\r\n");
      out.write("          <ul class=\"nav nav-1 nav-sidebar\">\r\n");
      out.write("            <li><a href=\"manage/apply.jsp#\">申请处理</a></li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main\">\r\n");
      out.write("          <h1 class=\"page-header\" id=\"C1\"><i class=\"fa fa-cog fa-spin\"></i>&nbsp;控制台<small>&nbsp;&nbsp;&nbsp;");
      out.print(basePath);
      out.write("<small id=\"C2\"></small></h1>\r\n");
      out.write("          <!--<h2 class=\"sub-header\">Section title</h2>-->\r\n");
      out.write("\t\t  <div id=\"content\">\t\t\r\n");
      out.write("\t\t\t<div class=\"panel panel-info\">\r\n");
      out.write("\t\t\t\t<div class=\"panel-heading\">\r\n");
      out.write("\t\t\t\t\t<h3 class=\"panel-title\">已出租占比：<small id=\"pgs2\" style=\"font-size: 15px;\"></small>\r\n");
      out.write("\t\t\t\t\t\t&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;月可收入：￥<small id=\"pgs3\" style=\"font-size: 15px;\"></h3>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"panel-body\">\r\n");
      out.write("\t\t\t\t\t<div class=\"progress progress-striped active\">\r\n");
      out.write("\t\t\t\t\t<div class=\"progress-bar\" role=\"progressbar\" aria-valuenow=\"60\" \r\n");
      out.write("\t\t\t\t\taria-valuemin=\"0\" aria-valuemax=\"100\" style=\"width: 0%;\" id=\"pgs\">\t\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<span class=\"sr-only\">40% 完成</span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"panel panel-warning\">\r\n");
      out.write("\t\t\t\t<div class=\"panel-heading\">\r\n");
      out.write("\t\t\t\t\t<h3 class=\"panel-title\">此处可修改房间租金</h3>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"panel-body\">\r\n");
      out.write("\t\t\t\t\t<form action=\"servlet/roomtable1?2\" method = \"post\">\r\n");
      out.write("\t\t\t\t\t<p><label style=\"font-size: 15px\">选择需要修改的房间：</label>\r\n");
      out.write("\t\t\t\t\t\t<select id=\"msg\" class=\"btn btn-default dropdown-toggle\" style=\"width: auto\" name=\"room\">\r\n");
      out.write("\t\t\t\t\t\t\t<option v-for=\"rm in room\" onClick=\"selroom();\">{{rm.room}}</option>\r\n");
      out.write("\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" placeholder=\"输入修改后的价格\" style=\"width:auto;height: auto\" name=\"price\">\r\n");
      out.write("\t\t\t\t\t\t&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t<button class=\"btn btn-warning\">修改</button>\r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t<div style=\"height: 250px; overflow: auto; margin-bottom: 20px\">\r\n");
      out.write("\t\t\t\t\t\t<table class=\"table table-striped table-hover\" id=\"t1\">\r\n");
      out.write("\t\t\t\t\t\t  <thead>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t  <th>房间</th>\r\n");
      out.write("\t\t\t\t\t\t\t  <th>租金</th>\r\n");
      out.write("\t\t\t\t\t\t\t  <th>状态</th>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t  </thead>\r\n");
      out.write("\t\t\t\t\t\t  <tbody>\r\n");
      out.write("\t\t\t\t\t\t\t<tr v-for=\"rm in room\" @click=\"msg(rm)\">\t\t<!-- v-for vue方法,把数组对应为一组元素-->\r\n");
      out.write("\t\t\t\t\t\t\t  <td>{{rm.room}}</td>\r\n");
      out.write("\t\t\t\t\t\t\t  <td>￥{{rm.price}}</td>\r\n");
      out.write("\t\t\t\t\t\t\t  <td>{{rm.state}}</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t  </tbody>\r\n");
      out.write("\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"panel panel-danger\">\r\n");
      out.write("\t\t\t\t<div class=\"panel-heading\">\r\n");
      out.write("\t\t\t\t\t<h3 class=\"panel-title\">此处可增/删房间</h3>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"panel-body\">\r\n");
      out.write("\t\t\t\t\t<div class=\"well col-sm-6\" style=\"height: 100px\"><label>增加：</label>\r\n");
      out.write("\t\t\t\t\t\t<form action=\"servlet/roomtable1?3\" method = \"post\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" placeholder=\"输入要增加房间的号码\" name=\"roomadd\">\r\n");
      out.write("\t\t\t\t\t\t<button class=\" btn btn-success\">增加</button>\r\n");
      out.write("\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"well col-sm-6\" style=\"height: 100px\"><label>删除：</label><br>\r\n");
      out.write("\t\t\t\t\t\t<form action=\"servlet/roomtable1?4\" method = \"post\">\r\n");
      out.write("\t\t\t\t\t\t<select id=\"msg2\" class=\"btn btn-default dropdown-toggle\" style=\"width: auto\" name=\"roomdel\">\r\n");
      out.write("\t\t\t\t\t\t\t<option v-for=\"rm in room\">{{rm.room}}</option>\r\n");
      out.write("\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t<button class=\" btn btn-danger\">删除</button>\r\n");
      out.write("\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t  </div>\r\n");
      out.write("\t\t  <script type=\"text/javascript\">\r\n");
      out.write("\t\t\t  $(function(){\r\n");
      out.write("\t\t\t\t  $.ajax({\r\n");
      out.write("\t\t\t\t\t  type:'get',\r\n");
      out.write("\t\t\t\t\t  url:'servlet/roomtable1?1',\r\n");
      out.write("\t\t\t\t\t  success:function(rs){\r\n");
      out.write("\t\t\t\t\t\t  //alert(rs);\r\n");
      out.write("\t\t\t\t\t\t  var arr=rs.split(\",\");\r\n");
      out.write("\t\t\t\t\t\t  var a= document.getElementById(\"pgs\");\r\n");
      out.write("\t\t\t\t\t\t  var b = document.getElementById('pgs2');\r\n");
      out.write("\t\t\t\t\t\t  var c = document.getElementById('pgs3');\r\n");
      out.write("\t\t\t\t\t\t  a.style.width=arr[0];\r\n");
      out.write("\t\t\t\t\t\t  b.innerHTML = arr[0];\r\n");
      out.write("\t\t\t\t\t\t  c.innerHTML = arr[1];\r\n");
      out.write("\t\t\t\t\t  },\r\n");
      out.write("\t\t\t\t\t  error:function(){\r\n");
      out.write("\t\t\t\t\t\t  alert(\"servlet error\")\r\n");
      out.write("\t\t\t\t\t  }\r\n");
      out.write("\t\t\t\t  })\r\n");
      out.write("\t\t\t\t  $.ajax({\r\n");
      out.write("\t\t\t\t\t\ttype:'get',\t\t\t\t\t//get或post\r\n");
      out.write("\t\t\t\t\t\turl:'servlet/roomtable?3',\r\n");
      out.write("\t\t\t\t\t\tsuccess: function(json){\t//请求成功返回数据\r\n");
      out.write("\t\t\t\t\t\t\t\tshow(json);\r\n");
      out.write("\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\terror: function(json){\r\n");
      out.write("\t\t\t\t\t\t\talert(JSON.stringify(json));\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\tfunction show(json){\r\n");
      out.write("\t\t\t\t\t\t// vue 进行渲染\r\n");
      out.write("\t\t\t\t\t\tvar obj=JSON.parse(json);\r\n");
      out.write("\t\t\t\t\t\t//使用JSON.parse把传回的String类型转位json类型\r\n");
      out.write("\t\t\t\t\t\tnew Vue({\r\n");
      out.write("\t\t\t\t\t\t\tel: '#msg',\r\n");
      out.write("\t\t\t\t\t\t\tdata:{\r\n");
      out.write("\t\t\t\t\t\t\t\t\troom:obj,\r\n");
      out.write("\t\t\t\t\t\t\t\t },\r\n");
      out.write("\t\t\t\t\t\t\tmethods:{\r\n");
      out.write("\t\t\t\t\t\t\t\tmsg:function(rm){\r\n");
      out.write("\t\t\t\t\t\t\t\t\talert(\"this\");\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\tnew Vue({\r\n");
      out.write("\t\t\t\t\t\t\tel: '#msg2',\r\n");
      out.write("\t\t\t\t\t\t\tdata:{\r\n");
      out.write("\t\t\t\t\t\t\t\t\troom:obj,\r\n");
      out.write("\t\t\t\t\t\t\t\t },\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\tnew Vue({\r\n");
      out.write("\t\t\t\t\t\t\tel: '#t1',\r\n");
      out.write("\t\t\t\t\t\t\tdata:{\r\n");
      out.write("\t\t\t\t\t\t\t\t\troom:obj,\r\n");
      out.write("\t\t\t\t\t\t\t\t },\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t  });\r\n");
      out.write("\t\t  </script>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"bootstrap-3.3.7-dist/js/bootstrap.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\tfunction load(){\r\n");
      out.write("\t\t\tif(");
      out.print(session.getAttribute("user"));
      out.write("==null){\r\n");
      out.write("\t\t\t\twindow.location.href=\"index.jsp\";\r\n");
      out.write("\t\t\t\talert(\"登录已过期！请重新登录\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
