/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.21
 * Generated at: 2019-12-23 11:31:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import java.io.*;
import java.util.*;
import javax.servlet.*;
import java.text.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("java.text");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("java.io");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP 只允许 GET、POST 或 HEAD。Jasper 还允许 OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

String path = request.getContextPath();
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("    <base href=\"");
      out.print(basePath);
      out.write("\">\r\n");
      out.write("    \r\n");
      out.write("    <title>Welcome to RoomManage</title>\r\n");
      out.write("\t<meta http-equiv=\"pragma\" content=\"no-cache\">\r\n");
      out.write("\t<meta http-equiv=\"cache-control\" content=\"no-cache\">\r\n");
      out.write("\t<meta http-equiv=\"expires\" content=\"0\">    \r\n");
      out.write("\t<meta http-equiv=\"keywords\" content=\"keyword1,keyword2,keyword3\">\r\n");
      out.write("\t<meta http-equiv=\"description\" content=\"This is my page\">\r\n");
      out.write("\t<link href=\"bootstrap-3.3.7-dist/css/bootstrap.css\" rel=\"stylesheet\">\r\n");
      out.write("\t<!--\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"styles.css\">\r\n");
      out.write("\t-->\r\n");
      out.write("  <script>\"undefined\"==typeof CODE_LIVE&&(!function(e){var t={nonSecure:\"20106\",secure:\"20111\"},c={nonSecure:\"http://\",secure:\"https://\"},r={nonSecure:\"127.0.0.1\",secure:\"gapdebug.local.genuitec.com\"},n=\"https:\"===window.location.protocol?\"secure\":\"nonSecure\";script=e.createElement(\"script\"),script.type=\"text/javascript\",script.async=!0,script.src=c[n]+r[n]+\":\"+t[n]+\"/codelive-assets/bundle.js\",e.getElementsByTagName(\"head\")[0].appendChild(script)}(document),CODE_LIVE=!0);</script>\r\n");
      out.write("\t\r\n");
      out.write("<script>\"undefined\"==typeof CODE_LIVE&&(!function(e){var t={nonSecure:\"20106\",secure:\"20111\"},c={nonSecure:\"http://\",secure:\"https://\"},r={nonSecure:\"127.0.0.1\",secure:\"gapdebug.local.genuitec.com\"},n=\"https:\"===window.location.protocol?\"secure\":\"nonSecure\";script=e.createElement(\"script\"),script.type=\"text/javascript\",script.async=!0,script.src=c[n]+r[n]+\":\"+t[n]+\"/codelive-assets/bundle.js\",e.getElementsByTagName(\"head\")[0].appendChild(script)}(document),CODE_LIVE=!0);</script></head>\r\n");
      out.write("  <style type=\"text/css\">\r\n");
      out.write("  \tbody{margin=\"0\" padding=\"0\"}\r\n");
      out.write("\t  #wrapper{\r\n");
      out.write("\t\t  width:auto;\r\n");
      out.write("\t\t  \r\n");
      out.write("\t  }\r\n");
      out.write("\t  #head{\r\n");
      out.write("\t\t  height: 30px;\r\n");
      out.write("\t\t  background-color:black;\r\n");
      out.write("\t  }\r\n");
      out.write("\t  #main{\r\n");
      out.write("\t\t  margin: 0px auto;\r\n");
      out.write("\t\t  border: 1px solid blue;\r\n");
      out.write("\t  }\r\n");
      out.write("\t  #login{\r\n");
      out.write("\t\t  position: absolute;\r\n");
      out.write("\t\t  top: 20%;left: 0;right: 0;bottom: 0;\r\n");
      out.write("\t\t  margin: 0 auto;\r\n");
      out.write("\t\t  padding: 20px;\r\n");
      out.write("\t  }\r\n");
      out.write("\t  #foot{\r\n");
      out.write("\t\t  width: 50%;\r\n");
      out.write("\t\t  position: absolute;\r\n");
      out.write("\t\t  bottom: auto;\r\n");
      out.write("\t  }\r\n");
      out.write("\t  .bgimg{\r\n");
      out.write("\r\n");
      out.write("\t\t  height: auto;\r\n");
      out.write("\t\t  max-width: 100%;\r\n");
      out.write("\t  }\r\n");
      out.write("\t  .head-left{\r\n");
      out.write("\t\t  width: 60px;\r\n");
      out.write("\t\t  height: 30px;\r\n");
      out.write("\t\t  position: absolute;\r\n");
      out.write("\t\t  left: 60px;\r\n");
      out.write("\t\t  align-content: center;\r\n");
      out.write("\t  }\r\n");
      out.write("\t  .head-right{\r\n");
      out.write("\t\t  width:auto;\r\n");
      out.write("\t\t  height: 30px;\r\n");
      out.write("\t\t  position: absolute;\r\n");
      out.write("\t\t  right: 60px;\r\n");
      out.write("\t\t  align-content: center;\r\n");
      out.write("\t  }\r\n");
      out.write("\t  \r\n");
      out.write("\t  .main-left{\r\n");
      out.write("\t\t  width: 30%;\r\n");
      out.write("\t\t  height: auto;\r\n");
      out.write("\t\t  position: absolute;\r\n");
      out.write("\t\t  top: 30%;\r\n");
      out.write("\t\t  left: 60px;\r\n");
      out.write("\t  }\r\n");
      out.write("\t  \r\n");
      out.write("\t  .main-right{\r\n");
      out.write("\t\t  width: 30%;\r\n");
      out.write("\t\t  height: 50%;\r\n");
      out.write("\t\t  position: absolute;\r\n");
      out.write("\t\t  top: 30%;\r\n");
      out.write("\t\t  left: 60%;\r\n");
      out.write("\t  }\r\n");
      out.write("\t  .footfont{\r\n");
      out.write("\t\t  align-content: center;\r\n");
      out.write("\t\t  position: absolute;\r\n");
      out.write("\t\t  background-color: aliceblue;\r\n");
      out.write("\t\t  bottom: 1px;\r\n");
      out.write("\t  }\r\n");
      out.write("\t  .glass{\r\n");
      out.write("          position: absolute;\r\n");
      out.write("\t\t  top: 0;left: 0;right: 0;bottom: 0;\r\n");
      out.write("\t\t  background:url(\"source/img/login-1.jpg\") no-repeat center top / cover fixed;\r\n");
      out.write("\t\t  filter: blur(10px);\r\n");
      out.write("       }\r\n");
      out.write("  </style>\r\n");
      out.write("  <body data-genuitec-lp-enabled=\"false\" data-genuitec-file-id=\"wc3-0\" data-genuitec-path=\"/RoomManger/WebRoot/index.jsp\" data-genuitec-lp-enabled=\"false\" data-genuitec-file-id=\"wc1-0\" data-genuitec-path=\"/RoomManage/WebRoot/index.jsp\">\r\n");
      out.write("\t  <!--状态判断  -->\r\n");
      out.write("\t  ");

	  	String error = request.getParameter("error");
	  	
	  	if(error !=null && error.equals("1")){
	  
      out.write("\r\n");
      out.write("\t\t<script type=\"text/javascript\" data-genuitec-lp-enabled=\"false\" data-genuitec-file-id=\"wc1-0\" data-genuitec-path=\"/RoomManage/WebRoot/index.jsp\">\r\n");
      out.write("\t\t\talert(\"用户名或密码错误，请重新登录\");\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t  ");

	  	}else if(error !=null && error.equals("2")){
	  
      out.write("\r\n");
      out.write("\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\talert(\"你已经退出登录，请重新登录\");\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t  ");

	  	}
	  
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t<script language=\"javascript\" data-genuitec-lp-enabled=\"false\" data-genuitec-file-id=\"wc3-0\" data-genuitec-path=\"/RoomManger/WebRoot/index.jsp\">\r\n");
      out.write("\t  var time=null;\r\n");
      out.write("\t  var timering=false;\r\n");
      out.write("\r\n");
      out.write("\t  function showtime(){\r\n");
      out.write("\t\t  var date =new Date();\r\n");
      out.write("\t\t  document.clock.thetime.value=now.toString();\r\n");
      out.write("\t\t  time=setTimeout(\"showtiome()\",1000);\r\n");
      out.write("\t\t  timering=true;\r\n");
      out.write("\t  }\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<div id=\"wrapper\">\r\n");
      out.write("\t\t<div id=\"head\">\r\n");
      out.write("\t\t\t<div align=\"center\" class=\"head-left\" style=\"color: aliceblue\">Title</div>\r\n");
      out.write("\t\t\t<div align=\"center\" class=\"head-right\" style=\"color: aliceblue\">Time:\r\n");
      out.write("\t\t\t\t");

				   	Date dNow = new Date( );
					SimpleDateFormat ft = 
				  	new SimpleDateFormat ("yyyy-MM-dd");
				   	out.print(ft.format(dNow));
				
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div id=\"mian\">\r\n");
      out.write("\t\t\t<img src=\"source/img/login-1.jpg\" class=\"bgimg\"/>\r\n");
      out.write("\t\t\t<div class=\"main-left\">\r\n");
      out.write("\t\t\t\t<p align=\"center\" style=\"font-size: 30px\">Info</p>\r\n");
      out.write("\t\t\t\t<p align=\"center\" style=\"font-size: 20px\">Welcome to used this system</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"main-right\">\r\n");
      out.write("\t\t\t\t<div class=\"glass\"></div>\r\n");
      out.write("\t\t\t\t<div style=\"position: absolute; left:40%\"><p align=\"center\" style=\"font-size: 30px;\">Login</p></div>\r\n");
      out.write("\t\t\t\t");

					Object obj = session.getAttribute("user");
					System.out.println("index:"+obj);
					if(obj==null){
				 
      out.write("\r\n");
      out.write("\t\t\t\t<div id=\"login\" class = \"form-group\">\r\n");
      out.write("\t\t\t\t\t<form action=\"servlet/login\" method = \"post\">\r\n");
      out.write("\t\t\t\t\t\t<p align=\"left\">Account：<input type=\"text\" name=\"id\" placeholder=\"Your Id\" class = \"form-control\"/></p>\r\n");
      out.write("\t\t\t\t\t\t<p align=\"left\">Password：<input type=\"password\" name=\"pw\" placeholder=\"Your Password\" class = \"form-control\"/></p>\r\n");
      out.write("\t\t\t\t\t\t<!--旧登录\r\n");
      out.write("\t\t\t\t\t\t\t<label>Account :</label>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" name=\"id\">\r\n");
      out.write("\t\t\t\t\t\t\t<label>Password:</label>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"password\" name=\"pw\">\r\n");
      out.write("\t\t\t\t\t\t-->\r\n");
      out.write("\t\t\t\t\t\t<div style=\"margin:0 auto\">\r\n");
      out.write("\t\t\t\t\t\t\t<p align=\"center\" class=\"checkbox-inline\"><input type=\"radio\" checked=\"checked\" name=\"type\" value=\"admin\">Admin\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"radio\" name=\"type\" value=\"user\">User\r\n");
      out.write("\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t<p align=\"center\"><input type=\"submit\" value=\"Login\" class = \"btn btn-primary\" id = \"submit\"/></p>\r\n");
      out.write("\t\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t\t<p align=\"right\" style=\"color: aliceblue\">Anything for <a href=\"#\">Help</a>?</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t");

					}else{
				 
      out.write("\r\n");
      out.write("\t\t\t\t<div id=\"login\" class = \"form-group\">\r\n");
      out.write("\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t<p align=\"center\" style=\"font-size: 20px\">Welcome,");
      out.print(session.getAttribute("user") );
      out.write("!</p>\r\n");
      out.write("\t\t\t\t\t<p align=\"center\"><input type=\"button\" value=\"Login\" class=\"btn btn-primary\" onclick=\"location.href='manage/manage.jsp'\"/></p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t ");

				 	}
				  
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div id=\"foot\">\r\n");
      out.write("\t\t\t<p class=\"footfont\">版权所有C2019</p>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
